// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


export const isDummyAuthEnabled = typeof window !== 'undefined' && 
  (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1');

const dummyUser = {
  id: "00000000-0000-0000-0000-000000000000",
  email: "dummy@example.com",
  role: "authenticated",
  aud: "authenticated",
  app_metadata: {},
  user_metadata: { full_name: "Elena Márquez" },
  created_at: new Date().toISOString()
};

const dummySession = {
  access_token: "dummy.jwt.token",
  refresh_token: "dummy.refresh.token",
  expires_in: 3600,
  token_type: "bearer",
  user: dummyUser
};

const dummyAuth = {
  getUser: async () => ({ data: { user: dummyUser }, error: null }),
  getSession: async () => ({ data: { session: dummySession }, error: null }),
  onAuthStateChange: (callback: any) => {
    setTimeout(() => {
      callback("SIGNED_IN", dummySession);
    }, 0);
    return {
      data: {
        subscription: {
          unsubscribe: () => {}
        }
      }
    };
  },
  signInWithPassword: async () => ({ data: { user: dummyUser, session: dummySession }, error: null }),
  signUp: async () => ({ data: { user: dummyUser, session: dummySession }, error: null }),
  signOut: async () => ({ error: null }),
};


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || (isDummyAuthEnabled ? 'https://dummy.supabase.co' : '');
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || (isDummyAuthEnabled ? 'sb_publishable_dummy' : '');

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (prop === 'auth' && isDummyAuthEnabled) {
      return dummyAuth;
    }
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

